# Generated by Django 3.1.4 on 2020-12-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_employee_work_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.employee')),
            ],
        ),
    ]
