# Generated by Django 3.1.4 on 2020-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='work_date',
            field=models.DateField(auto_now=True),
        ),
    ]
