# Generated by Django 3.1.4 on 2020-12-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_worktime_work_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='work_time',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='worktime',
            name='work_date',
            field=models.DateField(),
        ),
    ]
