# Generated by Django 3.1.4 on 2020-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201208_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='time',
            field=models.CharField(choices=[('Shift', (('8', '8'), ('16', '16'))), ('Other', (('l4', 'l4'), ('vacation', 'vacation'))), ('unknown', 'Unknown')], default=8, max_length=10),
        ),
    ]
